#include <Arduino.h>
extern int gear;         
extern int cSolenoid;  
extern int vehicleSpeed;
extern unsigned long lastSensorTime;
extern int spcSetVal;
extern int spcPercentVal;
extern int n2SpeedPulses;
extern int n3SpeedPulses;
extern int vehicleSpeedPulses;
extern int n2Speed;
extern int n3Speed;
extern unsigned int __bss_end;
extern unsigned int __heap_start;
extern void *__brkval;
extern int atfSensorFilterWeight; 
extern int atfSensorNumReadings; 
extern int atfSensorAverage;            
extern int shiftDropPressure;
extern int boostcount;
extern unsigned long int shiftStartTime;
extern unsigned long int shiftDuration;
extern int cSolenoidEnabled;
extern boolean incar;
extern boolean stick;
extern boolean manual;
extern boolean trans;
extern boolean sensors;
extern boolean tpsSensor;
extern boolean boostSensor;
extern boolean shiftBlocker;
extern boolean health;
extern boolean debugEnabled;
extern boolean fullAuto;
extern boolean boostLimit;
extern boolean drive;